"""
Local OCR fallback for full scan using saved screenshots instead of remote OCR API.

This module reads the per-phase screenshots generated by screen_capture.py and
extracts the same structured fields expected by full_scan/database persistence.
"""

from __future__ import annotations

import re
import json
from collections import Counter
from pathlib import Path

import cv2
import numpy as np
import pytesseract

from backend.config import config


_REGIONS: dict[str, tuple[int, int, int, int]] = {}


def _ensure_tesseract() -> None:
    if not config.is_loaded:
        config.load()
    pytesseract.pytesseract.tesseract_cmd = config.tesseract_path
    _load_regions()


def _load_regions() -> None:
    global _REGIONS
    if _REGIONS:
        return

    map_path = Path(config.get_coordinate_map_path())
    with open(map_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    _REGIONS = {
        key: tuple(value) for key, value in data.get("regions", {}).items()
    }


def _region(name: str) -> tuple[int, int, int, int] | None:
    roi = _REGIONS.get(name)
    if roi is None:
        return None
    return tuple(int(v) for v in roi)


def _load_image(path: Path) -> np.ndarray | None:
    if not path.exists():
        return None
    return cv2.imread(str(path))


def _crop(
    img: np.ndarray | None, roi: tuple[int, int, int, int] | None
) -> np.ndarray | None:
    if img is None or roi is None:
        return None
    x1, y1, x2, y2 = roi
    h, w = img.shape[:2]
    if x2 > w or y2 > h:
        return None
    cropped = img[y1:y2, x1:x2]
    return cropped if cropped.size else None


def _normalize_text(text: str) -> str:
    return " ".join((text or "").strip().split())


def _parse_compact_number(text: str) -> int:
    text = _normalize_text(text).replace(" ", "")
    text = re.sub(r"[^0-9KMBkmb,\.]", "", text)
    if not text:
        return 0

    multiplier = 1
    suffix = text[-1].upper()
    if suffix in {"K", "M", "B"}:
        text = text[:-1]
        multiplier = {"K": 1_000, "M": 1_000_000, "B": 1_000_000_000}[suffix]

    numeric = text.replace(",", "")
    if not numeric:
        return 0

    try:
        if "." in numeric:
            return int(float(numeric) * multiplier)
        return int(numeric) * multiplier
    except ValueError:
        return 0


def _ocr_variants(roi: np.ndarray, scale: float = 4.0) -> list[tuple[str, np.ndarray]]:
    gray = cv2.cvtColor(roi, cv2.COLOR_BGR2GRAY)
    enlarged = cv2.resize(gray, None, fx=scale, fy=scale, interpolation=cv2.INTER_CUBIC)
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8)).apply(enlarged)
    blurred = cv2.GaussianBlur(enlarged, (3, 3), 0)
    _, otsu = cv2.threshold(blurred, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
    _, otsu_inv = cv2.threshold(
        blurred, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU
    )
    adaptive = cv2.adaptiveThreshold(
        enlarged, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 31, 8
    )
    return [
        ("gray", enlarged),
        ("clahe", clahe),
        ("otsu", otsu),
        ("otsu_inv", otsu_inv),
        ("adaptive", adaptive),
    ]


def _ocr_best_numeric(roi: np.ndarray | None, *, scale: float = 4.0) -> tuple[str, int]:
    if roi is None or roi.size == 0:
        return "", 0

    cfg = '--psm 7 -c tessedit_char_whitelist="0123456789KMBkmb,."'
    candidates: list[tuple[str, int]] = []
    for _, variant in _ocr_variants(roi, scale=scale):
        raw = pytesseract.image_to_string(variant, config=cfg).strip()
        if raw:
            candidates.append((raw, _parse_compact_number(raw)))

    if not candidates:
        return "", 0

    candidates.sort(
        key=lambda item: (
            item[1] > 0,
            any(ch.upper() in {"K", "M", "B"} for ch in item[0]),
            len(re.sub(r"\D", "", item[0])),
        ),
        reverse=True,
    )
    return candidates[0]


def _clean_exact_name(text: str) -> str:
    text = _normalize_text(text)
    if not text:
        return ""
    text = re.sub(r'["\'|\\`~^]+', " ", text)
    return _normalize_text(text)


def _extract_name_from_raw(raw_text: str) -> str:
    raw_text = _normalize_text(raw_text)
    if not raw_text:
        return ""

    match = re.search(
        r"\bLord\b\s+(.*?)\s+\b(?:Power|Merits)\b",
        raw_text,
        flags=re.IGNORECASE,
    )
    if match:
        candidate = _clean_exact_name(match.group(1))
        if candidate:
            return candidate

    match = re.search(r"\bLord\b\s+(.+)$", raw_text, flags=re.IGNORECASE)
    if match:
        candidate = _clean_exact_name(match.group(1))
        if candidate:
            return candidate

    return _clean_exact_name(raw_text)


def _extract_profile_name(profile_img: np.ndarray | None) -> tuple[str, str]:
    roi = _crop(profile_img, _region("profile_name"))
    if roi is None:
        return "", ""

    whitelist = (
        "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
        "abcdefghijklmnopqrstuvwxyz"
        "0123456789 []()'\"|_-."
    )
    raw_candidates: list[str] = []
    for _, variant in _ocr_variants(roi, scale=4.0):
        for psm in ("7", "6", "11", "13"):
            raw = pytesseract.image_to_string(
                variant,
                config=f'--psm {psm} -c tessedit_char_whitelist="{whitelist}"',
            ).strip()
            if raw:
                raw_candidates.append(_normalize_text(raw))

    if not raw_candidates:
        return "", ""

    scored = []
    for raw in raw_candidates:
        clean = _extract_name_from_raw(raw)
        if clean:
            scored.append((raw, clean))

    if not scored:
        return raw_candidates[0], ""

    scored.sort(key=lambda item: (len(item[1]), len(item[0])), reverse=True)
    return scored[0]


def _extract_profile_power(profile_img: np.ndarray | None) -> tuple[str, int]:
    roi = _crop(profile_img, _region("profile_power"))
    return _ocr_best_numeric(roi, scale=5.0)


def _extract_building_level(building_img: np.ndarray | None) -> tuple[str, int]:
    roi = _crop(building_img, _region("building_level"))
    raw, _ = _ocr_best_numeric(roi, scale=8.0)
    if not raw:
        return "", 0
    match = re.search(r"(\d{1,3})", raw)
    return raw, int(match.group(1)) if match else 0


def _extract_pet_token(pet_img: np.ndarray | None) -> tuple[str, int]:
    roi = _crop(pet_img, _region("pet_token"))
    if roi is None or roi.size == 0:
        return "", 0

    gray = cv2.cvtColor(roi, cv2.COLOR_BGR2GRAY)
    scaled = cv2.resize(gray, None, fx=4.0, fy=4.0, interpolation=cv2.INTER_CUBIC)
    _, thresh_a = cv2.threshold(
        scaled, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU
    )
    kernel = np.ones((2, 2), np.uint8)
    eroded = cv2.erode(scaled, kernel, iterations=1)
    _, thresh_b = cv2.threshold(
        eroded, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU
    )
    clahe = cv2.createCLAHE(clipLimit=2.5, tileGridSize=(8, 8)).apply(scaled)
    _, thresh_c = cv2.threshold(
        clahe, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU
    )

    cfg = "--psm 7 -c tessedit_char_whitelist=0123456789"
    candidates: list[tuple[str, int]] = []
    for variant in (thresh_a, thresh_b, thresh_c):
        img = cv2.copyMakeBorder(variant, 20, 20, 20, 20, cv2.BORDER_CONSTANT, value=255)
        raw = pytesseract.image_to_string(img, config=cfg).strip()
        if raw:
            digits = re.sub(r"\D", "", raw)
            if digits:
                candidates.append((raw, int(digits)))

    if not candidates:
        return "", 0

    counts = Counter(value for _, value in candidates)
    by_value: dict[int, list[str]] = {}
    for raw, value in candidates:
        by_value.setdefault(value, []).append(raw)

    values = list(by_value.keys())
    for value in values:
        short = str(value)
        for other in values:
            long = str(other)
            if other != value and len(long) == len(short) + 1 and long.startswith(short):
                return by_value[value][0], value

    best_value = sorted(
        values,
        key=lambda v: (counts[v], -len(str(v)), v),
        reverse=True,
    )[0]
    return by_value[best_value][0], best_value


def _extract_resources(resources_img: np.ndarray | None) -> dict:
    resource_names = ("gold", "wood", "ore", "mana")
    result = {
        name: {"bag": 0, "total": 0, "bag_raw": "", "total_raw": ""}
        for name in resource_names
    }
    if resources_img is None:
        return result

    for res_name in resource_names:
        slots = {
            "bag": _region(f"res_{res_name}_item"),
            "total": _region(f"res_{res_name}_total"),
        }
        for slot_name, roi_box in slots.items():
            roi = _crop(resources_img, roi_box)
            raw, value = _ocr_best_numeric(roi, scale=4.0)
            result[res_name][slot_name] = value
            result[res_name][f"{slot_name}_raw"] = raw

    return result


def run_local_scan_ocr(device_dir: str | Path) -> dict:
    """OCR the captured per-phase screenshots from one scan directory."""
    _ensure_tesseract()

    device_dir = Path(device_dir)
    profile_img = _load_image(device_dir / "profile_full.png")
    resources_img = _load_image(device_dir / "resources_full.png")
    hall_img = _load_image(device_dir / "hall_full.png")
    market_img = _load_image(device_dir / "market_full.png")
    pet_img = _load_image(device_dir / "pet_token_full.png")

    if not any((profile_img is not None, resources_img is not None, hall_img is not None, market_img is not None, pet_img is not None)):
        return {
            "success": False,
            "text": "",
            "parsed": {},
            "error": f"No captured screenshots found in {device_dir}",
            "source": "local",
        }

    profile_raw_name, profile_name = _extract_profile_name(profile_img)
    power_raw, power_value = _extract_profile_power(profile_img)
    hall_raw, hall_level = _extract_building_level(hall_img)
    market_raw, market_level = _extract_building_level(market_img)
    pet_raw, pet_token = _extract_pet_token(pet_img)
    resources = _extract_resources(resources_img)

    raw_lines = [
        f"Lord: {profile_raw_name}",
        f"Power: {power_raw}",
        f"Hall: {hall_raw}",
        f"Market: {market_raw}",
        f"PetToken: {pet_raw}",
    ]
    for res_name in ("gold", "wood", "ore", "mana"):
        res = resources[res_name]
        raw_lines.append(
            f"{res_name.title()}: bag={res.get('bag_raw', '')} total={res.get('total_raw', '')}"
        )

    parsed = {
        "lord_name": profile_name,
        "power": power_value,
        "hall_level": hall_level,
        "market_level": market_level,
        "pet_token": pet_token,
        "resources": resources,
    }

    critical_count = sum(
        [
            int(bool(profile_name)),
            int(power_value > 0),
            int(hall_level > 0),
            int(market_level > 0),
            int(pet_token > 0),
            int(any(resources[name]["total"] > 0 for name in resources)),
        ]
    )

    return {
        "success": critical_count >= 4,
        "text": "\n".join(raw_lines),
        "parsed": parsed,
        "error": "" if critical_count >= 4 else "Local OCR confidence too low",
        "source": "local",
    }
